{% set name = "foundation-sites" %}
{% set version = "6.6.0" %}
{% set sha256 = "11896e8989c2df62a5fbc34dbb52290adf86fa5b61bcacd1f3eea9a52d7bf78f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zurb/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: |
    tgz=$(npm pack)
    npm install -g $tgz
  noarch: generic

requirements:
  build:
    - nodejs
    
test:
  commands:
    - npm list -g foundation-sites
  requires:
    - nodejs
   
about:
  home: https://github.com/zurb/foundation-sites
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The most advanced responsive front-end framework in the world. Quickly create prototypes and production code for sites that work on any kind of device.'
  description: |
    Foundation is the most advanced responsive front-end framework in the world.  
  doc_url: https://foundation.zurb.com/sites/docs/
  dev_url: https://github.com/zurb/foundation-sites

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
