travis:
  secure:
    BINSTAR_TOKEN: HXWqMoHczFUVC3yGx+Ln7l1vWfszqB5K1EqQyyHFAUMVwwfflwSBa0e1MorTfT3dCm048Rh3Dr8e3ut3ihNcRRFM9Uc0iUHjM4/Jk3mB6ZiV4Uplgh59EG9jpeHYC0m4UCakZ6XOxInSjAffWUKc4TZCLaGcPnSKUJ1RDiXX5hyIWAWGTGggguHE0GbWZUOSykqhk2EOolGJ5qVwG678zurm8F7o8J+etZ80EPnNdpFO2r6RoNvH2GbAGYrFC7/ebze4moPSNcb/BtTdVRmsIj/W7jB4rFL6aqAx1V61ymQYMdk6SLNqsVlk1h2VTHIxzcjV7RIH9W3Fol1L6Y6QBN+7PWwnehhJyu5Ggkwp3V3kfltjnnfwYlATb0funTTgW5bdkluVXfc9YsSn1qfngyGuITRVh+PWRUfjDpkI4HY1EMWS/i+qrTC7GOS1brg8aNqMeu2xKXtAc9woWgZSx6gJ3R8LvIwv9WPD+dZD1QuQsmdmVz21EG7GLCvP3bqKn2jy10dp2Nnslwqjrt5fOm2Zwm7CLvnK2lKJWHCK8J/RRP675AGYPW5cpgvQxJYdeI14fG4vyHcAgWTzLEmM27bLGxbnslAJYycnT647y+VCwx3JNZxQLoNbx1k20whzk2br6dB5Pz/XTZxMnZNLPw0y0i4R5IPM4eVBvkbJwuU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
