travis:
  secure:
    BINSTAR_TOKEN: PnxgAaRUjuu19jqjeDYZRXE6gvfs34uSlxrOirlTxQoZ10VBbOxol47PCWmVhk42wLRvBfC/H68oJEFCM5e/yjTym3ng99+Kj8Ob/fx0hCkpQpfCzXBizCJ7RhwvSG1J7rVi4VHFKhZwlZiu3eMOL5A9JlcPPhvOdEjNEl2Gc3waa4hfk4P9RbbfCdCzkSGpHXcfwmvrXwUPe0jGVWi4nPfB6Cm0lPZOjWVU2DeL/olLLxw+tilRzLc+qufWQQUL4/H5uQpvudzSvHLQuqiL3QT6wDpP8IwQn9y3+WoMQa8GBo3DV4dD11gM7FVQbbhTn5Fq81autsqinh7lxL6VsA4R0czoQOpT4MZLimsBr8eFUDxCK2n4aNEbQ4hvped4E70tv/IAnMsT54L2JEqsoWd7Sdf+MdRFAIYkn0FHf5qip4BXip5lpEl2uJ6juqokfiHP8ybFLFySO2/s0wYOZJu/7Ssu7sXTKBw9I8pe/qX2XxPJXUyQI+DtJekrodcHN2AsS8vZxNlGSHcNbKIeHUKhNf9Ayjp4JAR64flQJ2dScH4fEFreJ6ExgWmav4/Ao/eM+EPpKzH0RAzdzSaNWXpiEZuh6vjP+J9HamB6gWSNSfH0c/P17glFBpsgotaRnvPf7TF0MY09k3PRCQbIQjYKznWmrOVFKoaxLpetbH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
